---
name: 'Dependencies'
description: 'Install common dependencies for all our tools'

runs:
  using: "composite"
  steps:
    - name: install dependencies
      shell: bash
      if: ${{ env.action_status != 'skip' }}
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install libxml2-dev libbz2-dev;
          sudo apt-get install zlib1g-dev
          sudo apt-get install libicu-dev
        else
          brew install libxml2
          brew install icu4c
          brew install bzip2
          brew install zlib
        fi
#    - uses: LanguageMachines/ticcactions/add-icu@v1
