---
name: 'signal start or run to irc'
description: 'send startup notification to IRC'

inputs:
  module:
    description: who are we
    default: ${{ github.event.repository.name }}
    required: true

runs:
  using: "composite"
  steps:
    - name: shortmessage
      id: sm
      shell: bash
      run: |
        sm=$(echo "${{github.event.head_commit.message }}" | cut -c 1-40 )
        echo "sm=$sm" >> $GITHUB_OUTPUT

    - name: IRC notification of starting the builds
      uses: Gottox/irc-message-action@v2
      with:
        server: irc.uvt.nl
        channel: '#gitlama'
        nickname: GitHub
        message: >
          ${{ github.actor }} started a build of ${{ inputs.module }}
          [${{ github.ref_name }}]
          "${{ steps.sm.outputs.sm }}"
