name: 'IRC Status'
description: 'signal status message to IRC'

inputs:
  server:
    description: 'the IRC server'
    default: irc.uvt.nl
    required: true
  channel:
    description: 'the channel name'
    required: true
    default: '#gitlama'
  nickname:
    description: the nickname
    required: true
  module:
    description: 'name of the tool'
  step:
    default: build
    description: 'which step sends the message'
  branch:
    description: 'branch name'
    default: 'master'
  status:
    description: 'whats the status?'
    required: true
  details:
    description: 'details about the status'
    default: ''

runs:
  using: "composite"
  steps:
    - name: show val
      shell: bash
      run: echo "status=${{inputs.status}}"

    - name: Notify IRC of skipped case
      if: ${{ inputs.status == 'skip' }}
      uses: Gottox/irc-message-action@v2
      with:
        server: ${{ inputs.server }}
        channel: ${{ inputs.channel }}
        nickname: ${{ inputs.nickname }}
        message: "${{ inputs.module }} [${{ inputs.branch }}] ${{ inputs.step }} with ${{ matrix.compiler }} by ${{ github.actor }} on ${{ matrix.os }}: \u00035SKIPPED\u0003 ${{ inputs.details }}"

    - name: Notify IRC of failure
      if: ${{ inputs.status != '' && inputs.status != 'skip' }}
      uses: Gottox/irc-message-action@v2
      with:
        server: ${{ inputs.server }}
        channel: ${{ inputs.channel }}
        nickname: ${{ inputs.nickname }}
        message: "${{ inputs.module }} [${{ inputs.branch }}] ${{ inputs.step }} with ${{ matrix.compiler }} by ${{ github.actor }} on ${{ matrix.os }}: \u00034FAILED\u0003 in step ${{ inputs.status }} ${{ inputs.details }}"

    - name: Notify IRC of succes
      if: ${{ inputs.status == '' }}
      uses: Gottox/irc-message-action@v2
      with:
        server: ${{ inputs.server }}
        channel: ${{ inputs.channel }}
        nickname: ${{ inputs.nickname }}
        message: "${{ inputs.module }} [${{ inputs.branch }}] ${{ inputs.step }} with ${{ matrix.compiler }} by ${{ github.actor }} on ${{ matrix.os }}: \u00033SUCCESS\u0003 ${{ inputs.details }}"
