---
name: 'Add Textcat dependency'
description: 'Add textcat package on Linux, or install from scratch on Mac'

runs:
  using: "composite"
  steps:
    - name: doit
      shell: bash
      if: ${{ env.action_status == '' }}
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        if [ "$RUNNER_OS" != "Linux" ]; then
          git clone https://github.com/LibreOffice/libexttextcat/
          cd libexttextcat
          sh autogen.sh
          ./configure
          make
          sudo make install
          cd ..
        else
          sudo apt-get install libexttextcat-dev
        fi
