---
name: 'Add ICU dependency'
description: 'Add ICU package gcc on Linux, or install from scratch on Mac'

runs:
  using: "composite"
  steps:
    - name: Gnu Or Clang
      id: compiler
      shell: bash
      run: |
        cid=$(echo ${{matrix.compiler}} | cut -d\+ -f1)
        if [ "$cid" == "g" ]
        then
          cid=$cid"cc"
        fi
        echo "compiler=$cid" >> GITHUB_OUTPUT
    - name: install gcc version
      shell: bash
      if: |
        ${{ env.action_status == '' &&
        steps.compiler.outputs.compiler == 'gcc' }}
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        if [ "$RUNNER_OS" == "Linux" ]
        then
          sudo apt-get install libicu-dev
        else
          git clone https://github.com/unicode-org/icu.git
          cd icu/icu4c/source
          chmod +x runConfigureICU configure install-sh
          ./runConfigureICU macOS
          make # && make check
          sudo make install
          cd ../..
        fi
    - name: install clang version
      shell: bash
      if: |
        ${{ env.action_status == '' &&
        steps.compiler.outputs.compiler != 'gcc' }}
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install libicu-dev
        else
          brew install icu4c
        fi
